apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
  labels:
    app: multi-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
      containers:
        - name: container-1
          image: alpine
          command: ['/bin/sh', '-c']
          args:
            - >
              i=0;
              while true;
              do
                echo "$i: $(date)" >> /mount/log/${i}.log;
                i=$((i+1));
                sleep 60;
              done
          volumeMounts:
            - name: shared-volume
              mountPath: /mount
        - name: container-2
          image: alpine
          command: ['/bin/sh', '-c']
          args:
            - >
              i=0;
              while true;
              do
                echo "$i: $(date)" >> /mount/file/${i}.log;
                i=$((i+1));
                sleep 60;
              done
          volumeMounts:
            - name: shared-volume
              mountPath: /mount
